name: 🧪 Cucumber Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (17+ recommended)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Run Maven tests in headless mode
      # Make sure your Selenium code reads -Dheadless property
      - name: Run Cucumber Selenium Tests
        run: |
          mvn clean test -Dheadless=true

      # 5️⃣ Generate HTML report from cucumber.json
      - name: Generate Cucumber HTML Report
        run: |
          mvn net.masterthought:cucumber-reporting:generate

      # 6️⃣ Upload HTML report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jpetstore-test-report
          path: target/cucumber-html-report/**
