name: 🧪 Cucumber Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (21)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          # ⚠️ FIX: Temporarily change the cache key (e.g., add -v1) to force a cache miss.
          # This ensures the corrupted cucumber-reporting plugin is not restored.
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-v1
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Run Maven tests in headless mode
      - name: Run Cucumber Selenium Tests
        run: |
          # ⚠️ FIX: Added -U flag to force dependency updates/redownloads.
          mvn clean test -Dheadless=true -U

      # 5️⃣ Generate HTML report from cucumber.json
      - name: Generate Cucumber HTML Report
        run: |
          # ⚠️ FIX: Added -U flag here as well to ensure a clean plugin download/invocation.
          # This command will trigger the plugin execution.
          mvn net.masterthought:cucumber-reporting:generate -U

      # 6️⃣ Upload HTML report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jpetstore-test-report
          path: target/cucumber-html-report/**