name: 🧪 Cucumber Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (17+ recommended)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Force ChromeDriver symlink (avoids File exists error)
      - name: Force ChromeDriver symlink
        run: |
          sudo ln -sf /usr/bin/chromedriver /usr/bin/chromedriver

      # 5️⃣ Verify Chrome & ChromeDriver
      - name: Verify Chrome & ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      # 6️⃣ Run Maven tests in headless mode
      - name: Run Cucumber Selenium Tests
        run: |
          mvn clean test -Dheadless=true

      # 7️⃣ Upload HTML report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jpetstore-test-report
          path: target/cucumber-reports.html
