name: 🧪 Cucumber Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Bonus: Add a workflow_dispatch event for manual runs
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (17+ recommended)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Install Browser (REQUIRED for Selenium to run)
      - name: Setup Chrome/Chromedriver
        uses: browser-actions/setup-chrome@latest
        with:
          # This action ensures Chrome and the correct Chromedriver version are installed
          # and correctly added to the PATH for the tests to find.
          # If your tests use WebDriverManager, this step might be optional,
          # but it's the safest way to guarantee the browser is available.
          token: ${{ secrets.GITHUB_TOKEN }} # Use for rate limiting

      # 5️⃣ Run Maven tests in headless mode
      # NOTE: Ensure your test code reads the 'headless' property, e.g., System.getProperty("headless")
      - name: Run Cucumber Selenium Tests
        run: |
          mvn clean test -Dheadless=true

      # 6️⃣ Upload HTML report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          # Change the file name to the standard one for HTML reports (if you use Maven Cucumber Reporting)
          # A common path is 'target/site/cucumber-reporting/cucumber-html-reports/overview-features.html'
          # Check your project's configuration and adjust the path accordingly.
          name: jpetstore-test-report
          path: target/cucumber-reports.html
          # The path 'target/cucumber-reports.html' is a placeholder.
          # You must replace it with the actual path to your HTML report file.