name: 🧪 Cucumber Selenium CI
# ... (on and jobs sections remain the same) ...

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (21)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          # ⚠️ Use a unique key for now to ensure we don't restore the bad cache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-clean-v2
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Delete Corrupted Plugin from Cache
        # This command forcefully removes the specific folder for the reporting plugin.
        # This guarantees Maven MUST download a fresh copy.
        run: |
          rm -rf ~/.m2/repository/net/masterthought/cucumber-reporting/5.10.1

      # 5️⃣ Run Maven tests in headless mode
      - name: Run Cucumber Selenium Tests
        run: |
          # Use -U (Update) to confirm fresh downloads
          mvn clean test -Dheadless=true -U

      # 6️⃣ Generate HTML report from cucumber.json
      - name: Generate Cucumber HTML Report
        run: |
          # Use -U for the plugin execution as well
          mvn net.masterthought:cucumber-reporting:generate -U

      # 7️⃣ Upload HTML report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jpetstore-test-report
          path: target/cucumber-html-report/**